# Generated by Django 4.0.1 on 2022-01-26 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
