# Generated by Django 4.0.1 on 2022-01-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
